/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientProjectsRouteImport } from './routes/client.projects'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientChatRouteImport } from './routes/client.chat'
import { Route as ClientCalendarRouteImport } from './routes/client.calendar'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminFilesRouteImport } from './routes/admin.files'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as ClientProjectsIdRouteImport } from './routes/client.projects.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientChatRoute = ClientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCalendarRoute = ClientCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ClientRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const ClientProjectsIdRoute = ClientProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/chat': typeof ClientChatRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/chat': typeof ClientChatRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/calendar': typeof ClientCalendarRoute
  '/client/chat': typeof ClientChatRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/chat'
    | '/admin/files'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/client/calendar'
    | '/client/chat'
    | '/client/notifications'
    | '/client/profile'
    | '/client/projects'
    | '/admin/'
    | '/client/'
    | '/client/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/chat'
    | '/admin/files'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/client/calendar'
    | '/client/chat'
    | '/client/notifications'
    | '/client/profile'
    | '/client/projects'
    | '/admin'
    | '/client'
    | '/client/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/chat'
    | '/admin/files'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/client/calendar'
    | '/client/chat'
    | '/client/notifications'
    | '/client/profile'
    | '/client/projects'
    | '/admin/'
    | '/client/'
    | '/client/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/chat': {
      id: '/client/chat'
      path: '/chat'
      fullPath: '/client/chat'
      preLoaderRoute: typeof ClientChatRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/calendar': {
      id: '/client/calendar'
      path: '/calendar'
      fullPath: '/client/calendar'
      preLoaderRoute: typeof ClientCalendarRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/projects/$id': {
      id: '/client/projects/$id'
      path: '/$id'
      fullPath: '/client/projects/$id'
      preLoaderRoute: typeof ClientProjectsIdRouteImport
      parentRoute: typeof ClientProjectsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientProjectsRouteChildren {
  ClientProjectsIdRoute: typeof ClientProjectsIdRoute
}

const ClientProjectsRouteChildren: ClientProjectsRouteChildren = {
  ClientProjectsIdRoute: ClientProjectsIdRoute,
}

const ClientProjectsRouteWithChildren = ClientProjectsRoute._addFileChildren(
  ClientProjectsRouteChildren,
)

interface ClientRouteChildren {
  ClientCalendarRoute: typeof ClientCalendarRoute
  ClientChatRoute: typeof ClientChatRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientProjectsRoute: typeof ClientProjectsRouteWithChildren
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientCalendarRoute: ClientCalendarRoute,
  ClientChatRoute: ClientChatRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientProjectsRoute: ClientProjectsRouteWithChildren,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
